<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ai_interview_platform</RootNamespace>
    <UserSecretsId>cf44f8f8-1912-41f5-a806-4a1f5854b77a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="OpenAI" Version="2.13.0" />
  </ItemGroup>

</Project>
